/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.ControllerAlimento;
import Controller.ControllerPedido;
import Model.Alimento;
import Model.Bebida;
import java.util.List;
import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dante
 */
public class TelaBusca extends javax.swing.JPanel {

    /**
     * Creates new form TelaBusca1
     */
    public TelaBusca() {
        initComponents();
        listarAlimentos();
        configurarAtualizacaoAutomatica();
    }
    
     private void listarAlimentos() {
        String termo = txtBuscar.getText().trim();
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[]{"Nome", "Tipo", "Preço (R$)"}, 0
        );

        try {
            List<Alimento> lista;

            if (termo.isEmpty()) {
                lista = ControllerAlimento.listarTodos();
            } else {
                lista = ControllerAlimento.listarTodos(termo);
            }

            for (Alimento a : lista) {
                String tipo = (a instanceof Bebida) ? "Bebida" : "Comida";
                double precoFinal;

                if (a instanceof Bebida) {
                    Bebida b = (Bebida) a;
                    precoFinal = a.getPreco() + b.calcularImposto(); // preço + imposto
                } else {
                    precoFinal = a.getPreco();
                }

                modelo.addRow(new Object[]{
                    a.getNome(),
                    tipo,
                    String.format("R$ %.2f", precoFinal)
                });
            }

            tabelaAlimentos.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao listar alimentos: " + e.getMessage());
        }
    }

    private void configurarAtualizacaoAutomatica() {
        txtBuscar.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                listarAlimentos();
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                listarAlimentos();
            }
            @Override
            public void changedUpdate(DocumentEvent e) {
                listarAlimentos();
            }
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscar = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        tabelaAlimentos = new javax.swing.JTable();
        btnCarrinho = new javax.swing.JButton();

        txtBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtBuscar.setToolTipText("Busque por item");
        txtBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btnAdicionar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        tabelaAlimentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPane.setViewportView(tabelaAlimentos);

        btnCarrinho.setBackground(new java.awt.Color(204, 0, 51));
        btnCarrinho.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCarrinho.setForeground(new java.awt.Color(255, 255, 255));
        btnCarrinho.setText("Carrinho");
        btnCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarrinhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtBuscar))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        int linha = tabelaAlimentos.getSelectedRow();
    if (linha == -1) {
        JOptionPane.showMessageDialog(this, "Selecione um item primeiro!");
        return;
    }

    String nome = tabelaAlimentos.getValueAt(linha, 0).toString();
    Alimento alimento = ControllerAlimento.buscarPorNome(nome);

    if (alimento != null) {
        ControllerPedido.adicionarAoCarrinho(alimento);
        JOptionPane.showMessageDialog(this, nome + " adicionado ao carrinho!");
    }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarrinhoActionPerformed
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parentWindow instanceof TelaMenu telaMenu) {
            telaMenu.mostrarTela(new TelaCarrinho());
    }
    }//GEN-LAST:event_btnCarrinhoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCarrinho;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tabelaAlimentos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
