/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.ControllerAlimento;
import Controller.ControllerPedido;
import Model.ItemPedido;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dante
 */
public class TelaCarrinho extends javax.swing.JPanel {

    /**
     * Creates new form TelaPedido
     */
    public TelaCarrinho() {
        initComponents();
        atualizarTabela();
    }
    
    private void atualizarTabela() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[]{"Nome", "Qtd", "Preço (R$)"}, 0
        );
        double total = 0.0;

        for (ItemPedido item : ControllerPedido.getCarrinho()) {
            double preco = item.getAlimento().getPreco();

        if (item.getAlimento() instanceof Model.Bebida bebida && bebida.isAlcoolica()) {
            preco += bebida.calcularImposto();
        }

            double subtotal = preco * item.getQuantidade();
            total += subtotal;

            modelo.addRow(new Object[]{
                item.getAlimento().getNome(),
                item.getQuantidade(),
                String.format("R$ %.2f", subtotal)
            });
        }

        tabelaCarrinho.setModel(modelo);
        lblTotal.setText(String.format("Total: R$ %.2f", total));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCarrinho = new javax.swing.JScrollPane();
        tabelaCarrinho = new javax.swing.JTable();
        btnRemover = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();

        tabelaCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        panelCarrinho.setViewportView(tabelaCarrinho);

        btnRemover.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnRemover.setText("Remover selecionado");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnFinalizar.setBackground(new java.awt.Color(204, 0, 51));
        btnFinalizar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnFinalizar.setForeground(new java.awt.Color(255, 255, 255));
        btnFinalizar.setText("Finalizar pedido");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotal.setText("Total: R$ 0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCarrinho)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnRemover, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(btnFinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        removerItem();
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        finalizarPedido();
    }//GEN-LAST:event_btnFinalizarActionPerformed

    
    private void removerItem() {
        int linha = tabelaCarrinho.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um item para remover!");
            return;
        }

        String nome = tabelaCarrinho.getValueAt(linha, 0).toString();
        ControllerPedido.removerDoCarrinho(
            ControllerAlimento.buscarPorNome(nome)
        );
        atualizarTabela();

        if (ControllerPedido.getCarrinho().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Carrinho vazio!");
        }
    }

    private void finalizarPedido() {
        int usuarioId = 1; // substituir depois pelo ID real
        if (ControllerPedido.finalizarPedido(usuarioId)) {
            JOptionPane.showMessageDialog(this, "Pedido realizado com sucesso!");
            ControllerPedido.limparCarrinho();
            atualizarTabela();
        } else {
            JOptionPane.showMessageDialog(this, "Carrinho vazio!");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JScrollPane panelCarrinho;
    private javax.swing.JTable tabelaCarrinho;
    // End of variables declaration//GEN-END:variables
}
