/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.ControllerPedido;
import Model.Pedido;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dante
 */
public class TelaPedidos extends javax.swing.JPanel {
    
    // cache para mapear linha -> pedido
    private List<Pedido> pedidosCache;

    // formatador de data (ex.: 10/11/2025 03:58)
    private static final DateTimeFormatter FMT = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");


    /**
     * Creates new form TelaPedidos
     */
    public TelaPedidos() {
        initComponents();
        carregarPedidos();
        ajustarLarguras();
    }
    
    private void carregarPedidos() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[]{"Data do Pedido", "Itens", "Avaliação"}, 0
        ) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        };

        pedidosCache = ControllerPedido.listarPedidos();

        for (Pedido p : pedidosCache) {
            String dataFmt = p.getData()
                .toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDateTime()
                .format(FMT);

            String itensConcatenados = String.join(", ", p.getItensNomes());
            String estrelas = gerarEstrelas(p.getAvaliacao());
            modelo.addRow(new Object[]{ dataFmt, itensConcatenados, estrelas });
        }

        tabelaPedidos.setModel(modelo);
        ajustarLarguras(); // garante largura após setModel
    }
    
    private void ajustarLarguras() {

    // 0 = Data, 1 = Itens, 2 = Avaliação
    var cols = tabelaPedidos.getColumnModel();
    cols.getColumn(0).setPreferredWidth(160);  // Data
    cols.getColumn(1).setPreferredWidth(520);  // Itens (maior espaço)
    cols.getColumn(2).setPreferredWidth(90);   // Estrelas (pequena)

    // Centraliza as estrelinhas (opcional)
    javax.swing.table.DefaultTableCellRenderer center = new javax.swing.table.DefaultTableCellRenderer();
    center.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    cols.getColumn(2).setCellRenderer(center);
}


    private String gerarEstrelas(int nota) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < 5; i++) {
            sb.append(i < nota ? "★" : "☆");
        }
        return sb.toString();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPedidos = new javax.swing.JTable();
        btnAvaliar = new javax.swing.JButton();

        tabelaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaPedidos);

        btnAvaliar.setBackground(new java.awt.Color(204, 0, 51));
        btnAvaliar.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnAvaliar.setForeground(new java.awt.Color(255, 255, 255));
        btnAvaliar.setText("Avaliar");
        btnAvaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvaliarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(249, Short.MAX_VALUE)
                .addComponent(btnAvaliar, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(244, 244, 244))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAvaliar, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvaliarActionPerformed
        int linha = tabelaPedidos.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um pedido para avaliar!");
            return;
        }

        // usa o cache para garantir que a linha corresponde ao pedido certo
        int pedidoId = pedidosCache.get(linha).getId();

        String notaStr = JOptionPane.showInputDialog(this, "Dê uma nota de 0 a 5 estrelas:");
        if (notaStr == null) return;

        try {
            int nota = Integer.parseInt(notaStr.trim());
            if (nota < 0 || nota > 5) {
                JOptionPane.showMessageDialog(this, "A nota deve ser entre 0 e 5!");
                return;
            }
            ControllerPedido.avaliarPedido(pedidoId, nota);
            carregarPedidos(); // recarrega já com as estrelas atualizadas
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Digite um número válido!");
        }
        
        
    }//GEN-LAST:event_btnAvaliarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvaliar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaPedidos;
    // End of variables declaration//GEN-END:variables
}
